version: "3.8"

services:
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://${POSTGRES_USER:-tetrix_dev}:${POSTGRES_PASSWORD:-dev_pass}@db:5432/${POSTGRES_DB:-tetrix_dev}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.6-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tetrix_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_pass}
      POSTGRES_DB: ${POSTGRES_DB:-tetrix_dev}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.1-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_dev_data:
  redis_dev_data: