groups:
  - name: TelegramBot
    rules:
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: CPU usage is above 80% for 5 minutes

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: Memory usage is above 85% for 5 minutes

      - alert: RedisHighMemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis high memory usage
          description: Redis memory usage is above 80% for 5 minutes

      - alert: RedisConnectionsHigh
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of Redis connections
          description: Redis has over 1000 client connections

      - alert: PostgresHighConnections
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of Postgres connections
          description: PostgreSQL has over 80% of max_connections in use

      - alert: PostgresSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname="telegram_bot"}[1m]) > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow PostgreSQL queries detected
          description: Queries taking longer than 30 seconds detected

      - alert: TelegramWebhookErrors
        expr: rate(telegram_webhook_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Telegram webhook errors detected
          description: High rate of webhook errors in the last 5 minutes

      - alert: APIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High API latency detected
          description: 95th percentile of request duration is above 1 second

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for 5 minutes 