global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'telegram_bot'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 