"""add_language_field

Revision ID: 003_add_language_field
Revises: 002_update_telegram_data
Create Date: 2024-12-24 15:44:37.737562

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003_add_language_field'
down_revision = '002_update_telegram_data'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=2), nullable=False, server_default='ru'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ### 