name: Deploy Backend and Frontend

# Trigger on specific changes
on:
  push:
    branches: [ production ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'nginx/**'
      - 'docker-compose.prod.yml'
      - '.github/workflows/backend-deploy.yml'

jobs:
  initialize:
    runs-on: ubuntu-latest
    environment:
      name: production-init
      url: ${{ vars.PROD_HOST }}
    # This environment can be manually triggered again if needed
    
    steps:
    - uses: actions/checkout@v3

    # Generate self-signed SSL certificate for initial setup
    # (You can replace it later with a proper one)
    - name: Generate SSL Certificate
      run: |
        mkdir -p nginx/ssl
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout nginx/ssl/private.key \
          -out nginx/ssl/certificate.crt \
          -subj "/C=US/ST=CA/L=SF/O=TetrixHospital/CN=${PROD_HOST}"

    - name: Initial Server Setup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.PROD_HOST }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          # Update system and install dependencies
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y docker.io docker-compose git

          # Add user to docker group
          sudo usermod -aG docker $USER
          
          # Generate PostgreSQL password if not exists
          if [ ! -f /opt/tetrix-hospital/secrets/postgres_password.txt ]; then
            mkdir -p /opt/tetrix-hospital/secrets
            openssl rand -base64 32 > /opt/tetrix-hospital/secrets/postgres_password.txt
            chmod 600 /opt/tetrix-hospital/secrets/postgres_password.txt
          fi
          
          # Create required directories
          sudo mkdir -p ${{ vars.DEPLOY_PATH || '/opt/tetrix-hospital' }}
          sudo chown ${USER}:${USER} ${{ vars.DEPLOY_PATH || '/opt/tetrix-hospital' }}
          mkdir -p ${{ vars.DEPLOY_PATH || '/opt/tetrix-hospital' }}/backups/{postgres,redis}
          
          # Setup logging
          sudo mkdir -p /var/log/nginx
          sudo touch /var/log/tetrix-backup.log
          sudo chown ${USER}:${USER} /var/log/tetrix-backup.log
          sudo chmod 644 /var/log/tetrix-backup.log
          
          # Setup git
          cd ${{ vars.DEPLOY_PATH || '/opt/tetrix-hospital' }}
          git init
          git config --global --add safe.directory ${{ vars.DEPLOY_PATH || '/opt/tetrix-hospital' }}
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          
          # Setup directories
          mkdir -p nginx/ssl
          mkdir -p prometheus
          mkdir -p grafana/dashboards
          mkdir -p logs/redis
          
          # Make scripts executable
          chmod +x scripts/*.sh
          
          # Reload shell to apply docker group
          newgrp docker

    - name: Copy SSL Certificates
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.PROD_HOST }}
        key: ${{ secrets.PROD_SSH_KEY }}
        source: "nginx/ssl/*"
        target: "/opt/tetrix-hospital/nginx/ssl"
        strip_components: 2

    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.PROD_HOST }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /opt/tetrix-hospital
          
          # Sync repository to ensure latest code
          git fetch origin production
          git reset --hard origin/production
          
          # Build and update services
          if [[ "${{ steps.changed-files.outputs.backend }}" == "true" ]]; then
            echo "Building and updating backend service..."
            docker-compose -f docker-compose.prod.yml up -d --build app
          fi
          
          if [[ "${{ steps.changed-files.outputs.nginx }}" == "true" ]]; then
            echo "Building and updating nginx service..."
            docker-compose -f docker-compose.prod.yml up -d --build nginx
          fi
          
          # Clean only dangling images
          docker image prune -f

    # Verify deployment with retries
    - name: Check deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.PROD_HOST }}
        username: ${{ vars.PROD_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        env:
          APP_PORT: ${{ vars.APP_PORT || '5000' }}
        script: |
          # Wait for services to be healthy
          for i in {1..30}; do
            HEALTH_OK=true
            
            # Check backend if updated
            if [[ "${{ steps.changed-files.outputs.backend }}" == "true" ]]; then
              if ! curl -f "http://localhost:${APP_PORT}/health"; then
                HEALTH_OK=false
              fi
            fi
            
            if [[ "$HEALTH_OK" == "true" ]]; then
              echo "All services are healthy"
              exit 0
            fi
            
            echo "Waiting for services to be healthy... ($i/30)"
            sleep 2
          done
          echo "Services failed to become healthy"
          exit 1