name: Deploy App Only

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'  # Only run on production branch
    environment:
      name: production
      url: ${{ vars.BACKEND_URL }}
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sh
            fi
            
            cd /opt/tetrix-hospital && \
            git pull && \
            docker compose build app && \
            docker compose up -d app