name: Deploy App Only

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'  # Only run on production branch
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /opt/tetrix-hospital && \
            git pull && \
            docker ps | grep tetrix-hospital_app_1 && docker stop tetrix-hospital_app_1 || true && \
            docker ps -a | grep tetrix-hospital_app_1 && docker rm tetrix-hospital_app_1 || true && \
            docker build -t tetrix-hospital_app:latest . -f backend/Dockerfile && \
            docker-compose up -d app