name: Deploy App Only

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'  # Only run on production branch
    environment:
      name: production
      url: ${{ vars.BACKEND_URL }}
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sh
            fi
            
            # Ensure Docker daemon is running
            if ! systemctl is-active --quiet docker; then
              systemctl start docker
            fi
            
            # Save environment variables with proper formatting
            cat > /opt/tetrix-hospital/.env << EOL
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            API_KEY=${{ secrets.API_KEY }}
            BACKEND_URL=${{ vars.BACKEND_URL }}
            FRONTEND_URL=${{ vars.FRONTEND_URL }}
            EOL
            
            # Ensure proper permissions
            chmod 600 /opt/tetrix-hospital/.env
            
            cd /opt/tetrix-hospital && \
            git pull && \
            docker compose build app && \
            docker compose up -d app